//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.25 at 02:45:10 PM IST 
//


package com.ordercreation.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subTotal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="totalTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="totalFulfillmentCharges" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="submitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="customer" type="{http://schema.broadleafcommerce.org/co}customer"/>
 *         &lt;element name="fulfillmentGroups" type="{http://schema.broadleafcommerce.org/co}fulfillmentGroup"/>
 *         &lt;element name="orderItems" type="{http://schema.broadleafcommerce.org/co}orderItem"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderId",
    "subTotal",
    "totalTax",
    "totalFulfillmentCharges",
    "status",
    "submitDate",
    "customer",
    "fulfillmentGroups",
    "orderItems"
})
@XmlRootElement(name = "createOrder")
public class CreateOrder {

    @XmlElement(required = true)
    protected String orderId;
    protected double subTotal;
    protected double totalTax;
    protected double totalFulfillmentCharges;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar submitDate;
    @XmlElement(required = true)
    protected Customer customer;
    @XmlElement(required = true)
    protected FulfillmentGroup fulfillmentGroups;
    @XmlElement(required = true)
    protected OrderItem orderItems;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the subTotal property.
     * 
     */
    public double getSubTotal() {
        return subTotal;
    }

    /**
     * Sets the value of the subTotal property.
     * 
     */
    public void setSubTotal(double value) {
        this.subTotal = value;
    }

    /**
     * Gets the value of the totalTax property.
     * 
     */
    public double getTotalTax() {
        return totalTax;
    }

    /**
     * Sets the value of the totalTax property.
     * 
     */
    public void setTotalTax(double value) {
        this.totalTax = value;
    }

    /**
     * Gets the value of the totalFulfillmentCharges property.
     * 
     */
    public double getTotalFulfillmentCharges() {
        return totalFulfillmentCharges;
    }

    /**
     * Sets the value of the totalFulfillmentCharges property.
     * 
     */
    public void setTotalFulfillmentCharges(double value) {
        this.totalFulfillmentCharges = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the submitDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmitDate() {
        return submitDate;
    }

    /**
     * Sets the value of the submitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmitDate(XMLGregorianCalendar value) {
        this.submitDate = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link Customer }
     *     
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer }
     *     
     */
    public void setCustomer(Customer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the fulfillmentGroups property.
     * 
     * @return
     *     possible object is
     *     {@link FulfillmentGroup }
     *     
     */
    public FulfillmentGroup getFulfillmentGroups() {
        return fulfillmentGroups;
    }

    /**
     * Sets the value of the fulfillmentGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link FulfillmentGroup }
     *     
     */
    public void setFulfillmentGroups(FulfillmentGroup value) {
        this.fulfillmentGroups = value;
    }

    /**
     * Gets the value of the orderItems property.
     * 
     * @return
     *     possible object is
     *     {@link OrderItem }
     *     
     */
    public OrderItem getOrderItems() {
        return orderItems;
    }

    /**
     * Sets the value of the orderItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItem }
     *     
     */
    public void setOrderItems(OrderItem value) {
        this.orderItems = value;
    }

}
